version: "3"
services:
  springboot-app1:
    image: node-1
    build: .
    environment:
      PORT: 9000
    ports:
      - 9000:9000
    depends_on:
      - dbpostgresql
  dbpostgresql:
    container_name: some_postgres
    image: postgres:14.0
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: node_9000
