spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: loverloser
    url: jdbc:postgresql://localhost:5432/certificate_repository
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: validate

#logging:
#  file:
#    name: /logs/clevertec.log
#    path: /

server:
  port: 8080
