spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://dbpostgresql:5433/node_9000
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true


server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

#cluster:
#  nodes:
#    9000:
#      - 9000
#      - 9003
#      - 9004
#    9001:
#      - 9001
#      - 9005
#      - 9006
#    9002:
#      - 9002
#      - 9007
#      - 9008
